name: DockerBuild CI

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    tags:
      - v*

env:
  FRONTEND_IMAGE: neurocircuit-frontend
  BACKEND_IMAGE: neurocircuit-backend
  BACKEND_DIR: ./backend

jobs:
  update_req:
    if: github.ref=='refs/heads/main'
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
        
      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Compile requirements.txt
        working-directory: $${{ env.BACKEND_DIR }}
        run: uv pip compile pyproject.toml -o requirements.txt

      - name: Check for changes in requirements.txt
        id: check_changes
        run: |
          git diff --quiet ${{ env.BACKEND_DIR }}/requirements.txt || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ${{ env.BACKEND_DIR }}/requirements.txt
          git commit -m "chore: Update requirements.txt via CI"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Frontend docker image
        run: |
          docker build ./frontend -t $FRONTEND_IMAGE --label "runnumber=${GITHUB_RUN_ID}"
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Frontend docker image to GHCR
        run: |
          IMAGE_ID=ghcr.io/${{github.repository_owner}}/$FRONTEND_IMAGE

          #UPPERCASE->lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]') 

          #strips the git ref prefix from the version.
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          #strips the "v" prefix from the tag name.
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $FRONTEND_IMAGE $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Build Backend docker image
        run: |
          docker build ./backend -t $BACKEND_IMAGE --label "runnumber=${GITHUB_RUN_ID}"

      - name: Push Backend docker image to GHCR
        run: |
          IMAGE_ID=ghcr.io/${{github.repository_owner}}/$BACKEND_IMAGE

          #UPPERCASE->lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]') 

          #strips the git ref prefix from the version.
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          #strips the "v" prefix from the tag name.
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $BACKEND_IMAGE $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION